#!/bin/bash

if [ "Linux" != "$(uname -s)" ]; then
    echo "You can only build this on a Linux host."
    exit 2
fi

if [ -n "$(git status --porcelain)" ]; then
    echo
    echo "There are uncommitted modifications - are you absolutely sure you want to make a package???"
    echo
fi

DESCRIBE=$(git describe)
INSTALL_PATH='.stack-work/install/x86_64-*/lts-2.*/7.*/bin'

stack clean
stack build --optimizations

mkdir -p target
tar czf target/apvi-webservice-${DESCRIBE}.tar.gz \
  -C ${INSTALL_PATH} \
    apvi-webservice
