#!/bin/bash

cabal sandbox init
cabal clean
cabal install -j --only-dependencies
cabal build

mkdir target
tar czf target/apvi-webservice-`date +%Y-%m-%d-%H%M%S-%Z`.tar.gz \
  dist/build/apvi-webservice/apvi-webservice \
  .cabal-sandbox/share/x86_64-linux-ghc-7.8.4/Chart-diagrams-1.4/fonts
