#!/bin/bash

if [ "Linux" != "$(uname -s)" ]; then
    echo "You can only build this on a Linux host."
    exit 2
fi

if [ -n "$(git status --porcelain)" ]; then
    echo
    echo "There are uncommitted modifications - are you absolutely sure you want to make a package???"
    echo
fi

DESCRIBE=$(git describe)

cabal sandbox init

# NOTE: make sure the aemo-archiver is available at the path below!
cabal sandbox add-source ../aemo-archiver

cabal clean
cabal install -j --only-dependencies
cabal build

mkdir -p target
tar czf target/apvi-webservice-${DESCRIBE}.tar.gz \
  dist/build/apvi-webservice/apvi-webservice \
  .cabal-sandbox/share/x86_64-linux-ghc-7.8.4/Chart-diagrams-1.5/fonts
